module.exports = {
  'signin via email for temp-2' : function (browser) {
    browser
      .url(browser.globals.urls.memberurl)
      .windowMaximize("current")
      .waitForElementVisible('body', 1000)
      .saveScreenshot('./screenshots/signin.png')
      .useXpath()
      .click("//div[@id='template-2']/div/div/div/div[2]/a[1]")
      .pause(4000)
      .click("//div[6]/div/div/div[2]/div/div/a/div")
      .pause(4000)
      .click("(//input[@id='login_email'])[6]")
      .pause(4000)
      .setValue("(//input[@id='login_email'])[6]", browser.globals.email)
      .pause(4000)
      .click("(//input[@id='login_password'])[6]")
      .pause(4000)
      .setValue("(//input[@id='login_password'])[6]", browser.globals.password)
      .pause(4000)
      .click("(//button[@type='submit'])[6]")
      .pause(2000)
      .click('link text', "Test Activity offer")
      .pause(2000)
      .click("//a[@class='btn btn-color btn-lg']")
      .pause(2000)
      .click("(//img[@alt='4'])[1]")
      .pause(2000)
      .click("(//a[@class='save-state-link'])[1]")
      .pause(2000)
      .window_handles(function(result) {
       var handle = result.value[1]
      browser.switchWindow(handle)
   })
      .pause(2000)
      .click("//input[@type='text']")
      .pause(2000)
      .setValue("//input[@type='text']",browser.globals.facebookemail)
      .pause(2000)
      .click("//input[@type='password']")
      .pause(2000)
      .setValue("//input[@type='password']",browser.globals.facebookpw)
      .pause(2000)
      .click("//button[@value='1']")
      .pause(2000)
      .click("(//button[@type='submit'])[2]")
      .pause(2000)
      .click("(//button[@type='submit'])[3]")
      .pause(2000)
      .click("(//button[@type='submit'])[3]")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .click("(//button[@class='btn btn-color btn-block'])[1]")
      .pause(2000)
      .click("(//label[@class='control-checkbox'])[1]")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .click("(//button[@class='btn btn-color btn-block'])[2]")
      .pause(2000)
      .click("(//label[@class='control-checkbox'])[2]")
      .pause(2000)
      .click("(//a[@class='save-state-link'])[1]")
      .pause(2000)
      .window_handles(function(result) {
       var handle = result.value[1]
      browser.switchWindow(handle)
   })
      .pause(2000)
      .click("//input[@class='text']")
      .pause(2000)
      .setValue("//input[@class='text']",browser.globals.twitteremail)
      .pause(2000)
      .click("//input[@type='password']")
      .pause(2000)
      .setValue("//input[@type='password']",browser.globals.twitterpw)
      .pause(2000)
      .click("(//input[@type='submit'])[1]")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .click("(//textarea[@id='shares__text'])[3]")
      .pause(2000)
      .setValue("(//textarea[@id='shares__text'])[3]",'Tw seed phrase')
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .click("(//textarea[@id='shares__text'])[4]")
      .pause(2000)
      .setValue("(//textarea[@id='shares__text'])[4]",'Greece is a country in southeastern Europe with thousands of islands throughout the Aegean and Ionian seas' )
      .pause(2000)
      .click("(//label[@class='control-checkbox'])[3]")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .setValue("(//input[@type='file'])[1]",require('path').resolve('C:/Users/Sukada/Desktop/image4.jpg'))
      .pause(2000)
      .click("(//button[@class='btn btn-color btn-block'])[3]")
      .pause(2000)
      .click("(//label[@class='control-checkbox'])[4]")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .setValue("(//input[@type='file'])[2]",require('path').resolve('C:/Users/Sukada/Desktop/image4.jpg'))
      .pause(2000)
      .click("(//button[@class='btn btn-color btn-block'])[4]")
      .pause(2000)
      .click("(//label[@class='control-checkbox'])[5]")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .setValue("(//input[@type='file'])[3]",require('path').resolve('C:/Users/Sukada/Desktop/image3.jpg'))
      .pause(2000)
      .click("(//textarea[@id='shares__text'])[7]")
      .pause(2000)
      .setValue("(//textarea[@id='shares__text'])[7]",'Tw photo seed phrase')
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .click("(//textarea[@id='shares__text'])[8]")
      .pause(2000)
      .setValue("(//textarea[@id='shares__text'])[8]",'abc.com')
      .pause(2000)
      .click("(//label[@class='control-checkbox'])[6]")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .click("(//textarea[@id='shares__text'])[9]")
      .pause(2000)
      .setValue("(//textarea[@id='shares__text'])[9]",'https://youtu.be/jTt5MglRGUQ')
      .pause(2000)
      .click("(//label[@class='control-checkbox'])[7]")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .click("(//textarea[@id='shares__text'])[10]")
      .pause(2000)
      .setValue("(//textarea[@id='shares__text'])[10]",'https://www.pinterest.com/pin/455426581058936706/')
      .pause(2000)
      .click("(//label[@class='control-checkbox'])[8]")
      .pause(2000)
      .click("//a[@class='save-state-link']")
      .pause(2000)
      .window_handles(function(result) {
       var handle = result.value[1]
      browser.switchWindow(handle)
   })
      .pause(2000)
      .click("//input[@name='username']")
      .pause(2000)
      .setValue("//input[@name='username']",browser.globals.instaemail)
      .pause(2000)
      .click("//input[@name='password']")
      .pause(2000)
      .setValue("//input[@name='password']",browser.globals.instapw)
      .pause(2000)
      .click("//input[@type='submit']")
      .pause(2000)
      .click("(//input[@type='submit'])[2]")
      .pause(3000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .click("(//textarea[@id='shares__text'])[11]")
      .pause(2000)
      .setValue("(//textarea[@id='shares__text'])[11]",'https://www.instagram.com/p/BLrYElKBbyD/?taken-by=sukadar')
      .pause(2000)
      .click("(//label[@class='control-checkbox'])[9]")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .setValue("(//input[@type='file'])[4]",require('path').resolve('C:/Users/Sukada/Desktop/image3.jpg'))
      .pause(2000)
      .click("(//label[@class='control-checkbox'])[10]")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .click("//input[@ng-model='new_name']")
      .pause(2000)
      .setValue("//input[@ng-model='new_name']",'Sarah')
      .pause(2000)
      .click("//input[@ng-model='new_email']")
      .pause(2000)
      .setValue("//input[@ng-model='new_email']",'sukada.ramakrishna@socialmedialink.com')
      .pause(2000)
      .click("//textarea[@id='shares__message']")
      .pause(2000)
      .setValue("//textarea[@id='shares__message']",'Party at 283,Nwe york on the 8th Nov at 12:00PM')
      .pause(2000)
      .click("//div[@class='col-sm-2 col-xs-12 col10']")
      .pause(2000)
      .click("(//a[@class='sharing-list-buttons-show'])[1]")
      .pause(2000)
      .click("//textarea[@id='shares__bazaarvoice_title']")
      .pause(2000)
      .setValue("//textarea[@id='shares__bazaarvoice_title']",'This is Title')
      .pause(2000)
      .click("(//textarea[@id='shares__text'])[12]")
      .pause(2000)
      .setValue("(//textarea[@id='shares__text'])[12]",'This is a test product review description written to test the sharing tool')
      .pause(2000)
      .click("(//img[@alt='4'])[2]")
      .pause(2000)
      .click("//button[@class='btn btn-primary btn-banner']")
      .pause(2000)
      .click("(//button[@type='button'])[34]")
      .pause(2000)
      .end();
  }
}
