module.exports = {
  email:'avari@yopmail.com',
  username:'avari',
  password:'general1234',
  firstname:'sukada',
  lastname:'rao',
  zipcode:'10018',
  postalcode:'K1A0B1',
  dob:'10-10-1980',
  lcn:'123456789012',
  adminemail:'test@yopmail.com',
  adminpassword:'General1234#',
  surveyname:'survey',
  activityname:'Test Activity',
  bvstagingclnttoken:'caEg1TBXTKhIcmnk623URKYPzAYlrtoLG2LkHaqD4neTk',
  bvstagingenkey:'6VgQ5XhdqOaVnj2FlvjqjMTxc',
  bvstagingprodid:'Product10',
  facebookemail:'sukada.testmember8@socialmedialink.com',
  facebookpw:'general1234',
  twitteremail:'sukada.ramakrishna@socialmedialink.com',
  twitterpw:'general1234',
  instaemail:'sukadar',
  instapw:'general1234',
 urls:{
    memberurl:'https://sukadaspri92.staging.socialmedialink.com/home#/',
    adminurl:'https://admin.staging.socialmedialink.com',
    adminyoutubeurl:'https://www.youtube.com/watch?v=cmSbXsFE3l8',
 }

};
