module.exports = {
  'signup via email for temp-2' : function (browser) {
  browser
      .url(browser.globals.urls.memberurl)
      .windowMaximize("current")
      .waitForElementVisible('body', 1000)
      .useXpath()
      .click("(//a[@class= 'btn create-account themed-button'])[2]")
      .pause(4000)
      .click("(//div[@class='button-label'])[16]")
      .pause(4000)
      .click("(//input[@id='member_email'])[6]")
      .pause(4000)
      .setValue("(//input[@id='member_email'])[6]",browser.globals.email)
      .pause(2000)
      .click("(//input[@id='member_password_invisible'])[6]")
      .pause(2000)
      .setValue("(//input[@id='member_password_invisible'])[6]", browser.globals.password)
      .pause(2000)
      .click("(//input[@id='member_loyalty_card_number'])[6]")
      .pause(2000)
      .setValue("(//input[@id='member_loyalty_card_number'])[6]",browser.globals.lcn)
      .pause(2000)
      .click("(//input[@id='age_requirement'])[6]")
      .pause(2000)
      .click("(//button[@type='submit'])[6]")
      .pause(3000)
      .url('http://www.yopmail.com/en/')
      .windowMaximize("current")
      .click("//input[@id='login']")
      .pause(3000)
      .setValue("//input[@id='login']",browser.globals.username)
      .pause(5000)
      .click("//input[@value='Check Inbox']")
      .pause(2000)
      .frame('ifmail')
      .pause(2000)
      .click("//a[@class='mcnButton']")
      .pause(4000)
      .window_handles(function(result) {
       var handle = result.value[1]
      browser.switchWindow(handle)
   })
      .click("(//input[@id='member_email'])[6]")
      .pause(2000)
      .click("(//input[@id='member_first_name'])[6]")
      .pause(2000)
      .setValue("(//input[@id='member_first_name'])[6]",browser.globals.firstname)
      .pause(2000)
      .click("(//input[@id='member_last_name'])[6]")
      .pause(2000)
      .setValue("(//input[@id='member_last_name'])[6]",browser.globals.lastname)
      .pause(2000)
      .click("(//select[@id='member_country'])[6]")
      .pause(2000)
      .click("(//select[@id='member_country'])[6]/option[1]")
      .pause(2000)
      .click("(//input[@id='member_zip_code'])[6]")
      .pause(2000)
      .setValue("(//input[@id='member_zip_code'])[6]",browser.globals.zipcode)
      .pause(2000)
      .click("(//input[@id='member_birthday'])[6]")
      .pause(2000)
      .setValue("(//input[@id='member_birthday'])[6]",browser.globals.dob)
      .pause(2000)
      .click("(//select[@id='member_gender'])[6]")
      .pause(2000)
      .click("(//select[@id='member_gender'])[6]/option[3]")
      .pause(2000)
      .assert.visible("(//div[@class='dialog form-fieldset'])[3]/button")
      .pause(2000)
      .click("(//div[@class='dialog form-fieldset'])[3]/button")
      .pause(2000)
      .saveScreenshot('./screenshots/register-result.png')
      .pause(5000)
      .end();
 }
};
