module.exports = {
  'signup via email for temp-2' : function (browser) {
  browser
      .url(browser.globals.urls.adminurl)
      .windowMaximize("current")
      .waitForElementVisible('body', 1000)
      .useXpath()
      .click("//input[@type='email']")
      .setValue("//input[@type='email']",browser.globals.adminemail)
      .pause(2000)
      .click("//input[@type='password']")
      .pause(1000)
      .setValue("//input[@type='password']",browser.globals.adminpassword)
      .pause(1000)
      .click("//input[@type='submit']")
      .pause(1000)
      .click("//a[@class='test-nav-hubs']")
      .pause(1000)
      .click("//a[@class='btn btn-default btn-icon-add test-hub-new']")
      .pause(1000)
      .click("//input[@class='form-control ng-pristine ng-valid']")
      .pause(1000)
      .setValue("//input[@class='form-control ng-pristine ng-valid']",browser.globals.surveyname)
      .pause(2000)
      .click("//button[@class='btn btn-default']")
      .pause(2000)
      .click("(//span[@class='icon-survey'])[1]")
      .pause(3000)
      .click("//span[@class='table-icon icon-survey-small']")
      .pause(3000)
      .click("(//li[@class='js-draggable test-survey-new-single_answer ui-draggable'])[1]")
      .pause(2000)
      .click("//textarea[@rows='1']")
      .pause(2000)
      .setValue("//textarea[@rows='1']",'single answer')
      .pause(2000)
      .click("(//button[@type='button'])[4]")
      .pause(2000)
      .click("(//textarea[@rows='1'])[3]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[3]",'a')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .click("(//textarea[@rows='1'])[4]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[4]",'b')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .click("(//textarea[@rows='1'])[5]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[5]",'c')
      .pause(2000)
      .click("(//button[@type='button'])[7]")
      .pause(2000)
      .click("//li[@class='test-question-new test-question-new-multiple_answers']")
      .pause(2000)
      .click("//textarea[@class='q-field q-field-large test-question-name ng-pristine ng-valid']")
      .pause(2000)
      .clearValue("//textarea[@class='q-field q-field-large test-question-name ng-pristine ng-valid']")
      .pause(2000)
      .setValue("//textarea[@class='q-field q-field-large test-question-name ng-pristine ng-valid']",'Multiple Answers')
      .pause(2000)
      .click("(//textarea[@rows='1'])[3]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[3]",'a')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .click("(//textarea[@rows='1'])[4]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[4]",'b')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .pause(2000)
      .click("(//textarea[@rows='1'])[5]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[5]",'c')
      .pause(2000)
      .click("(//button[@type='button'])[7]")
      .pause(2000)
      .click("//li[@class='test-question-new test-question-new-single_image']")
      .pause(2000)
      .click("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .clearValue("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[1]",'Single Image')
      .pause(2000)
      .setValue("//div[@class='btn button b-upload-dropzone__btn test-question-imageanswer-upload']/input[@type='file']", require('path').resolve('C:/Users/Sukada/Desktop/image2.jpg'))
      .pause(2000)
      .click("(//textarea[@type='text'])[2]")
      .pause(2000)
      .setValue("(//textarea[@type='text'])[2]",'aa')
      .pause(2000)
      .setValue("//div[@class='btn button b-upload-dropzone__btn test-question-imageanswer-upload']/input[@type='file']", require('path').resolve('C:/Users/Sukada/Desktop/image1.jpg'))
      .pause(2000)
      .click("(//textarea[@type='text'])[4]")
      .pause(2000)
      .setValue("(//textarea[@type='text'])[4]",'bb')
      .pause(2000)
      .setValue("//div[@class='btn button b-upload-dropzone__btn test-question-imageanswer-upload']/input[@type='file']", require('path').resolve('C:/Users/Sukada/Desktop/image3.jpg'))
      .pause(2000)
      .click("(//textarea[@type='text'])[6]")
      .pause(2000)
      .setValue("(//textarea[@type='text'])[6]",'cc')
      .pause(2000)
      .click("(//button[@type='button'])[13]")
      .pause(2000)
      .click("//li[@class='test-question-new test-question-new-multiple_images']")
      .pause(2000)
      .click("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .clearValue("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[1]",'Multiple Images')
      .pause(2000)
      .setValue("//div[@class='btn button b-upload-dropzone__btn test-question-imageanswer-upload']/input[@type='file']", require('path').resolve('C:/Users/Sukada/Desktop/image2.jpg'))
      .pause(2000)
      .click("(//textarea[@rows='1'])[3]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[3]",'aa')
      .pause(2000)
      .setValue("//div[@class='btn button b-upload-dropzone__btn test-question-imageanswer-upload']/input[@type='file']", require('path').resolve('C:/Users/Sukada/Desktop/image1.jpg'))
      .pause(2000)
      .click("(//textarea[@rows='1'])[5]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[5]",'bb')
      .pause(2000)
      .setValue("//div[@class='btn button b-upload-dropzone__btn test-question-imageanswer-upload']/input[@type='file']", require('path').resolve('C:/Users/Sukada/Desktop/image3.jpg'))
      .pause(2000)
      .click("(//textarea[@rows='1'])[7]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[7]",'cc')
      .pause(2000)
      .click("(//button[@type='button'])[13]")
      .pause(2000)
      .click("//li[@class='test-question-new test-question-new-matrix_with_single_answer']")
      .pause(2000)
      .click("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .clearValue("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[1]",'Matrix Single')
      .pause(2000)
      .click("(//textarea[@rows='1'])[3]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[3]",'aa')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .click("(//textarea[@rows='1'])[4]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[4]",'bb')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .click("(//textarea[@rows='1'])[5]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[5]",'cc')
      .pause(2000)
      .click("(//textarea[@rows='1'])[6]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[6]",'a')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .click("(//textarea[@rows='1'])[7]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[7]",'b')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .pause(2000)
      .click("(//textarea[@rows='1'])[8]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[8]",'c')
      .pause(2000)
      .click("//button[@class='btn button test-question-create']")
      .pause(2000)
      .click("//li[@class='test-question-new test-question-new-matrix_with_multiple_answers']")
      .pause(2000)
      .click("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .clearValue("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[1]",'Matrix Multiple')
      .pause(2000)
      .click("(//textarea[@rows='1'])[3]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[3]",'aa')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .click("(//textarea[@rows='1'])[4]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[4]",'bb')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .click("(//textarea[@rows='1'])[5]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[5]",'cc')
      .pause(2000)
      .click("(//textarea[@rows='1'])[6]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[6]",'a')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .click("(//textarea[@rows='1'])[7]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[7]",'b')
      .pause(2000)
      .keys(browser.Keys.ENTER)
      .pause(2000)
      .click("(//textarea[@rows='1'])[8]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[8]",'c')
      .pause(2000)
      .saveScreenshot('./screenshots/register-result.png')
      .pause(2000)
      .click("//button[@class='btn button test-question-create']")
      .pause(2000)
      .click("//li[@class='test-question-new test-question-new-yes_or_no']")
      .pause(2000)
      .click("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .clearValue("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[1]",'Yes or No')
      .pause(2000)
      .click("//button[@class='btn button test-question-create']")
      .pause(2000)
      .click("//li[@class='test-question-new test-question-new-text']")
      .pause(2000)
      .click("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .clearValue("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[1]",'Text')
      .pause(2000)
      .click("//button[@class='btn button test-question-create']")
      .pause(2000)
      .click("//li[@class='test-question-new test-question-new-numbers']")
      .pause(2000)
      .click("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .clearValue("(//textarea[@rows='1'])[1]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[1]",'Numbers')
      .pause(2000)
      .click("(//button[@type='button'])[3]")
      .pause(2000)
      .click("//a[@class='test-hub-link']")
      .pause(2000)
      .click("//a[@class='rowclick test-hub-structure-item-link ng-binding']")
      .pause(2000)
      .click("//button[@class='btn-edit']")
      .pause(2000)
      .clearValue("//body[@id='admin']/div/div/div/div[2]/div/input")
      .pause(2000)
      .setValue("//body[@id='admin']/div/div/div/div[2]/div/input",'Survey')
      .pause(2000)
      .click("(//div[@class='q-list-link q-list-reward'])[1]")
      .pause(2000)
      .setValue("//input[@type='text']",'50')
      .pause(2000)
      .click("(//button[@class='btn btn-primary q-list-done'])[1]")
      .pause(2000)
      .click("//strong[@class='q-list-type-badge']")
      .pause(2000)
      .setValue("//div[@class='btn btn-upload test-promo-image-upload btn-primary']/input[@type='file']",require('path').resolve('C:/Users/Sukada/Desktop/image4.jpg'))
      .pause(2000)
      .click("//textarea[@class='form-control q-list-badge-name test-activity-badge-name ng-pristine ng-valid placeholder']")
      .pause(2000)
      .setValue("//textarea[@class='form-control q-list-badge-name test-activity-badge-name ng-pristine ng-valid placeholder']",'testbadge')
      .pause(2000)
      .click("//li[@class='q-list-item-section']/div/button[1]")
      .pause(2000)
      .click("//div[@ng-app ='app.questions']/div/nav/ul/li[2]")
      .pause(2000)
      .click("//textarea[@type='text']")
      .pause(2000)
      .setValue("//textarea[@type='text']", 'Test Survey')
      .pause(2000)
      .click("(//textarea[@rows='1'])[2]")
      .pause(2000)
      .setValue("(//textarea[@rows='1'])[2]",'Tagline')
      .pause(2000)
      .click("//textarea[@rows='7']")
      .pause(2000)
      .setValue("//textarea[@rows='7']",'This is a survey description')
      .pause(2000)
      .click("(//button[@type='button'])[7]")
      .pause(2000)
      .click("//a[@class='test-hub-link']")
      .pause(2000)
      .click("//a[@class=' test-hub-nav-logic']")
      .pause(2000)
      .click("//div[@class='mlogic-title ng-binding']")
      .pause(2000)
      .click("(//label[@class='control-checkbox control-checkbox-primary'])[1]")
      .pause(2000)
      .click("//input[@class='form-control ng-pristine ng-valid ng-valid-number']")
      .pause(2000)
      .setValue("//input[@class='form-control ng-pristine ng-valid ng-valid-number']",'1')
      .pause(2000)
      .click("//span[@ng-show='rule.members_groups.length == 0']")
      .pause(2000)
      .click("(//label[@class='control-checkbox control-checkbox-primary'])[3]")
      .pause(2000)
      .click("//button[@class='btn btn-primary test-hub-logic-item-group-save']")
      .pause(2000)
      .click("//input[@id='date-start']")
      .pause(2000)
      .click("//td[@class='active day']/preceding-sibling::td[@class='day'][1]")
      .pause(2000)
      .click("//label[@class='switcher ng-scope']")
      .pause(2000)
      .assert.visible("//button[@class='btn btn-default pull-right test-hub-logic-save']")
      .pause(2000)
      .click("//button[@class='btn btn-default pull-right test-hub-logic-save']")
      .pause(2000)
      .saveScreenshot('./screenshots/register-result.png')
      .pause(2000)
      .end();

  }
};
